name: Deploy to Heroku
on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/build/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: backend/src/main/resources/static
      - name: Build Backend
        run: mvn -B package --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: backend-build
          path: backend/target/app.jar  # app name (matches with final name in pom and Dockerfile)

  deploy:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
      name: Produktion Heroku
      url: https://gefahrometer-capstone.herokuapp.com/ # url of heroku app
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Heroku Key: will be replaced in GitHub
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: backend-build
          path: backend/target
      - name: Login to Heroku
        run: heroku container:login
      - name: Push Docker Image
        run: heroku container:push web -a gefahrometer-capstone # name of the heroku app
      - name: Release Docker Container
        run: heroku container:release web -a gefahrometer-capstone # name of the heroku app